INSERT INTO Utilizator VALUES 
('Huruiala','Carmen Alexandra'),
('Schornig','Petre'),
('Graur','Alexandra-Cristina'),
('Rudnitchi','Marian'),
('Anghel','Alin-Ilie'),
('Ristea','Ioan Fanica'),
('Hiliti','Nicolae'),
('Beizdadea','Cristiana'),
('Clitman','Jean'),
('Tudorica','Crsitian'),
('Robu','Simona Cristina'),
('Novac','Costel'),
('Mihalea','Radu Florin'),
('Verciuc','Nicu Adrian'),
('Jianu','Stefan-Calin'),
('Nan','Tolontan'),
('Achim','Andrei Cosmin'),
('Ocica','Fecioru'),
('Tanvuia','Alexandru - Cristian'),
('Feldman','Petre'),
('Coman','Alexandru Alin'),
('Dumitrescu','Doirian'),
('Stroilescu','Violeta Gabriela'),
('Mihaita','Andreea-Oana'),
('Claudia','Florian-Cosmin'),
('Bulete','Bilc'),
('Vladescu','Sorin Eugen'),
('Bardan','Lutea'),
('Dulea','Stefan Alexndru'),
('Niculescu','Dan Constantin'),
('Slavic','Ciprian Costel'),
('Buia','Denisa-Elena'),
('Caldararu','Ana Maria Alexandra'),
('Jarlaeanu','Aurel Mihai'),
('Vascan','Adrian Dragos'),
('Mateizer','Dragos Marian'),
('Ciuchi','Sânziana-Elena'),
('Claudia','Necula'),
('Gabriel','Liviu Daniel'),
('Mutulescu','Gabriela Violeta'),
('Istudor','Nicusor-Dorinel'),
('Vladuta','Laura'),
('Pandele','Daniel'),
('Mihalache','Andrei - Willi'),
('Boca','Irina-Alexandra'),
('Adochitei','Andreea-Elena'),
('Dulgheru','Gabriel'),
('Stoleru','Aurel Florian'),
('Bordea','Radu Florin'),
('Hozoc','Nicu Adrian'),
('Acatrinei','Monica'),
('Voiteanu','Cosmin - Cristian'),
('Gherman','Alina Elena'),
('Campian','Bogdan Adrian'),
('Handra','Aurelian-Stefan'),
('Virgolici','Boby'),
('Branza','Adrian Teodor'),
('Niculescu','Laura Florina'),
('Bica','Vasile Andrei'),
('Licu','Adrian Ionuţ'),
('Vutan','Sandrino-Gabriel'),
('Lichiardopol','Alexandru Cătălin'),
('Constandache','Georgian-Marian'),
('Chihaia','Cornelia'),
('Aciu','Stefan-Daniel'),
('Lentoiu','Panait'),
('Zoltan','Anca-Andreea'),
('Ceausu','Malina'),
('Placinta','Asandei'),
('Cirstea','Dragos-Ionuţ'),
('Stumbea','Cristian Andrei'),
('Ionut','Viorel'),
('Ganga','Nistor'),
('Magla','Cristina Elena'),
('Joian','Alexandra - Corina'),
('Slavic','Violeta Gabriela'),
('Siminoc','Cosmin-Ioan'),
('Birgaoanu-Acaei','Luigi'),
('Pantea','Panait'),
('Ionut','Crintea'),
('Balasel','Radu-Virgil'),
('Patrascu','Razvan-Eugen'),
('Calugaru','Daniel - Claudiu'),
('Pacurar','Bogdan-Leonard'),
('Cirstea','Mara Elena'),
('Cernica','Vlad George'),
('Antal','Serghei'),
('Radulescu-Stinga','Valentin Cosmin'),
('Bradeanu','Garbia'),
('Baltatescu','Nicolae Robert'),
('Hanches','Crsitian'),
('Corodeanu','Mircea Alexandru'),
('Gabriel Mihai','Vasile-Alexandru'),
('Marinache','Mihai Florian'),
('Giaba','Sergiu Cătălin'),
('Nena','Irina Laura'),
('Lixandru','Paul - Vlad'),
('Sipu','Luiza'),
('Poncea','Sergiu'),
('Udubasa','Cristian Ioan'),
('Minich','Alexandru Vlad'),
('Fetic','Alexandra Florina'),
('Drogeanu','Violeta Gabriela'),
('Babiciu','Mihai-Daniel'),
('Ceica','Bogdan-Daniel'),
('Domsa','Livius'),
('Inscriere','Ionelia Iuliana'),
('Surdu','Alexandru Ovidiu '),
('Biter','Denisa-Elena'),
('Mazalu','Doirian'),
('Caba ','Ioan'),
('Verciuc','Lori'),
('Buia','Bianca'),
('Dulharu','De Test'),
('Manailescu','Mihail Bogdan'),
('Ciprian','Paula'),
('Ivascu','Ioana-Lorina'),
('Kerekes','Ciprian'),
('Bunica','Adrian Bogdan'),
('Buia','Danut Valentin'),
('Marinache','Dragos- Corneliu'),
('Mustata','Mirela'),
('Patrascu','Florian'),
('Muscă','Radu Florin'),
('Spânu','Claudiu Florin'),
('Barjovanu','Denisa-Elena'),
('Marinescu','Kenibasov'),
('Hairedin','Marian Florin'),
('Pisla','Gedo'),
('Draguleasa','Eduard Mihail'),
('Bunoaica','Sânziana-Elena'),
('Noaghea','Mihail-Iulian'),
('Petica','Cornea'),
('AlexandruMedesan','Cristian - Andrei'),
('Bina','Raluca'),
('Mihaita','Octavian'),
('Lichi','Mirela Rocxana'),
('Fecioru','Kenibasov'),
('Bleanda-Mogosanu','Parasca'),
('Buznosu','Daniel - Claudiu'),
('Ghimpu','Alexandra Raluca'),
('Cortojan','Cristina'),
('Abramov','Luigi'),
('Giurgiu','Carlugea'),
('Viciu','Alina Mihaela'),
('Copae','Olga'),
('Corbu','Livius'),
('Borza','Bogdan Ionuţ'),
('Vutan','Cătălin Florin'),
('Gruia','Robert'),
('Stoleru','Mihai - Ionuţ'),
('Mazare','Alin-Ilie'),
('Istrate','Nicolae Petrut'),
('Galescu','Craita'),
('Tausancea','Ioan Andrei'),
('Dupir','Nicolae Cristian'),
('Tranca','Ioana Mihaela'),
('Zabava','Andreas'),
('Constandache','Cioaca'),
('Chiriac','Veronica'),
('Stancia','Cătălina Ioana'),
('Turiga','Veronica Flavia'),
('Leuciuc','Claudia'),
('Gigirtu','Mihai Marius'),
('Vizireanu','Iulian-Daniel'),
('Ludu','Marius Adrian'),
('Birgaoanu-Acaei','Bogdan Cosmin'),
('Pricope','Cristian - Mihai'),
('Denca','Ionuţ-Razvan'),
('Mircioiu','Silviu Adrian'),
('Hava','Jean'),
('Angelescu','Laurentiu-George'),
('Caia','Doirian'),
('Niculcea','Cătălina Ioana'),
('Minescu','Fareta'),
('Calugaru','Barlea'),
('Sterian','Violeta Gabriela'),
('Calugaru','Alina Cristina'),
('Grigor','Dan Cosmin'),
('Bratunov','Alexandru Dan'),
('Mihaileanu','Magda Marina'),
('Zegheanu','Iulia Hortensia'),
('Ciolpan','Prenume'),
('Aaron','Elama'),
('Matache','Remus - Gabriel'),
('Vaduvoiu','Alexandra - Corina'),
('Ungureanu','Marian Constantin'),
('Formagiu','Ovidiu - Cosmin'),
('Ghidan','Alex'),
('Mihaita','Aurelian Andrei'),
('Barac','Daniela-Alina'),
('Paius','Laurentiu'),
('Dragan','Paul Cosmin'),
('Butucelea','Alexandru Stefan'),
('Ceausi','Constantin Cătălin'),
('Barbulescu','Veronica'),
('Caramet','Valentin Sever'),
('Harlea','Mihail-Iulian'),
('Cociuban','Oana Ramona'),
('Chiriac','Adrian-Mihai'),
('Petrovici','Alis'),
('Banici','Alexandru Lucian'),
('Branet','Magda Marina'),
('Ivlev','Liviu Eugen'),
('Marinache','Fanica'),
('Viorel','Andreea-Oana'),
('Ocica','Laura'),
('Floarea','Luigi'),
('Boldeiu','Andrei-Stefan'),
('Turcoman','Mihaela-Viorica'),
('Mandita','Petre'),
('Perianu','Ovidiu - Cosmin'),
('Voinea','Marius Gabriel'),
('Bardan','Andrei Lucian'),
('Stefan','Sandrino-Gabriel'),
('Tuzar','Veronica Flavia'),
('Condrea','Sorin Ilie'),
('Parasca','Denisa-Elena'),
('Dabu','Mirel Alexandru'),
('Barac','Radoveanu'),
('Dragne','Raul'),
('Victor','Dragos-Florian'),
('Baciu','Florina'),
('Caracaş','Alexandr'),
('Pantea','Mara Elena'),
('Birgaoanu-Acaei','Elena-Ramona'),
('Scrobota','Daniel-Andrei'),
('Isacenco','Gheorghe'),
('Bradeanu','Adina-Ioana'),
('Vasilescu','Cristinel'),
('Ceafalau','Alexandru Dan'),
('Lixandru','Mihai Florian'),
('Razvan Anton','Ioan-Alexandru'),
('Caragheorghii','Cernea'),
('Daniela','Petru'),
('Rebrisoreanu','Ladislau'),
('Efrim','Gheorghe'),
('Crutan','Adrian-Marian'),
('Iacob','Gabriel George'),
('Preda','Eugen Gabriel'),
('Bozonc','Gheorghe'),
('Pampu','Razvan-Eugen'),
('Fratila','Bogdan Claudiu'),
('Ghita Petrache','Elama'),
('Pricope','Stefan-Daniel'),
('Cindea','Florin Eugen'),
('Scurtu-Andrei','Ionuţ Cristian'),
('Cusma','Bogdan Cosmin'),
('Morosanu','Marian Marius'),
('Iamandi','Danut Valentin'),
('Opris','Bejan'),
('Cernica','Adina-Maria'),
('Bleotu','Dan Constantin'),
('Ciolompea','Flaviu'),
('Stoicescu','Lucia-Ionela'),
('Alexandru','Matei'),
('Puscasu','Popa'),
('Nena','Adina-Minodora'),
('Turcu','Ilie Daniel'),
('Monoreanu','Nicoleta'),
('Dulea','Nicusor-Dorinel'),
('Sorin','Mihail Florian'),
('Iconaru','Ioan Romica'),
('Varjoghe','Sergiu Cristian'),
('Samoila','Eusebiu'),
('Geanta','Ana-Alina'),
('Elena','Mihail-Razvan'),
('Grosoiu','Ionuţ Constantin'),
('Vacalie','Cătălin Florin'),
('Stoica','Ioan-Alexandru'),
('Radulescu-Stinga','Puscasu'),
('Caras','Irina-Alexandra'),
('Surdu','Nedelea'),
('Manailescu','Serban-Ciprian'),
('Cuconu','Suzana'),
('Bolea','Gheorghe'),
('Baiu','Nicolae Robert'),
('Caragheorghii','Adrian Ion'),
('Victor','Toma'),
('Hodivoianu','Laurentiu-George'),
('Peter','Radu Stefan'),
('Stanca','Daniel-Laurentiu'),
('Ludu','Stoian'),
('Corodeanu','Zara'),
('Strambu','Liviu Stefan'),
('Achim','Corneliu Mihai'),
('Chesoi','Iulian-Daniel'),
('Cusma','Stefan-Calin'),
('Oprisor','Nicolae florin'),
('Hrisca','Adriana-Ioana'),
('Efrim','Mircea Alexandru'),
('Bica','Vladimir'),
('Nicolaescu','Mirela'),
('Drogeanu','Radu Stefan'),
('Minciuna','Nicolae Aurelian'),
('Mosorescu','Florian'),
('Rotaru','Titus'),
('Iorgus','Ragea'),
('Plesita','Andreea'),
('Iulian','Andrei-Stefan'),
('Pisica','Fareta'),
('Chitiburea','Adriana-Ioana'),
('Buleteanu','Andrei Ionuţ'),
('Negoita','Alexandru Cătălin'),
('Rolea','Ioana-Corina'),
('Tatasel','Marius Alexandru'),
('Frincu','Cătălin-Ionuţ'),
('Deftu','Valeria'),
('Aparaschivei','Andrei Sorin'),
('Gersak','Vlad Andrei'),
('Plesita','Stefan Calin'),
('Simu','Marius Adrian'),
('Penes','Ovidiu Stefan'),
('Baciu','Silviu Adrian'),
('Vlad','Anderi Octavian'),
('Le','Flaviu'),
('Patrasinca','Bogdan Eugen'),
('Dulharu','Cernea'),
('Grigore','Alina Liliana'),
('Kochan','Bogdan Alexandru'),
('Alexandru','Nedelea'),
('Mera','Alexandra Florina'),
('Matei','Lucia-Ionela'),
('Dupir','Mihail Florian'),
('Caracaş','Stefan Alexndru'),
('Le','Julia'),
('Calugaru','Nicolae Corneliu'),
('Sala','George Razvan'),
('Langa','Calin'),
('Mosorescu','Tiberiu Valentin'),
('Pascanu','Tudor Doru'),
('Hanches','Vasile Andrei'),
('Cican','Nicolae Corneliu'),
('Plesita','Craita'),
('Ciubuc','Mihai Serban'),
('Lehman','Bogdan Andrei'),
('Garbia','Ioana-Lorina'),
('Maldaianu','Valerian-Ionuţ'),
('Badeci','Raducu Ionuţ'),
('Kochan','Mario'),
('Jucan','Adrian Ion'),
('Giaba','Adrian Marius'),
('Huzum','Ramona'),
('Pirlog','Ionuţ-Cristian'),
('Lenard','Andreea Nicoleta'),
('Calance','Mihaela Cristina'),
('Vicol','Stefan Sorin'),
('Draghici','Cuculeac'),
('Branciog','Liviu Eugen'),
('Condrea','Fanica'),
('Constandache','Florentina Raluca'),
('Banarescu','Iulia-Georgiana'),
('Socol','Ionuţ Andrei'),
('Huzum','Bogdan Cezar'),
('Peter','Ghoerghe-Ionuţ'),
('Buia','Zoltan'),
('Sterian','Laurentia'),
('Iulian','Abel'),
('Miron','Bontas'),
('Rebrisoreanu','Valentin'),
('Marinache','Petronela Ana'),
('Iconaru','Julia'),
('Pesu','Andrei-Stefan'),
('Frunza','Paris'),
('Vlad','Virgil Gabriel'),
('Spiridon','Bogdan Cristian'),
('Buica','Ionuţ Alexandru'),
('Talpa','Dan Marius'),
('Miuta','Mihai - Ionuţ'),
('Sovarel','Ionuţ-Cristian'),
('Cristu','Oana'),
('Pristavu','Adrian Dragos'),
('Dimache','Cavill'),
('Sancraian','Alexis'),
('Enciu','Marius Emil'),
('Adamescu','Carol'),
('Claudia','Alina-Cristina'),
('Mares','Iulian-Cosmin'),
('Tudose','Ionuţ Gabriel'),
('Vatavu','Laurentiu-George'),
('Nistor','Ciprian Octavian'),
('Pelin','Costel Lucian'),
('Ilina','Bogdan Gabriel'),
('Ciolacu','Adrian Marius'),
('Danalachi','Andreea'),
('Pandele','Remus - Gabriel'),
('Negoita','Valentin Daniel'),
('Mares','Liviu Stefan'),
('Iorgulescu','Mihaela Roxana'),
('Hirsu','De Test'),
('Deaconu','Alexandru'),
('Lingureanu','Simona'),
('Botoc','Anton Iulian'),
('Turlete','Paul - Cristian'),
('Verciuc','Alexandru Laurentiu'),
('Hriscanu','David'),
('Dumitrache','Cristian-Stefan'),
('Caramida','De Test'),
('Serdaru','Stefan-George'),
('Buleteanu','Violeta Gabriela'),
('Tabara','Daniela Raluca'),
('Harlav','Ana Maria'),
('Pampu','Florin Eugen'),
('Ciungulescu','Alexandru-Bogdan'),
('Manolache','Ciprian Victor'),
('Vladulescu','Bocai'),
('Noaghea','Eugen Bogdan'),
('Bolohan','Cosmin Daniel'),
('Ghimpu','Alexandru-Dan'),
('Kerekes','Viorel Sebastian'),
('Copaceanu','Gratian'),
('Budescu','Corina Raluca'),
('Trandafir','Mihail-Iulian'),
('Cone','Mihai Cosmin'),
('Garbia','Bogdan Mihai'),
('Dubiczki','Andrei Marius'),
('Hapa','Dan Marius'),
('Terpezan','Lucian'),
('Tudose','Theodor Mugurel'),
('Motoi','Bogdan-Leonard'),
('Dumitrescu','Laurentiu-George'),
('Parvulescu','Iordan'),
('AlexandruMedesan','Mihail Gabriel'),
('Norocel','Remus - Gabriel'),
('Lichi','Andrei-Silviu'),
('Verciuc','Stefania'),
('Ignat','Marius Dan'),
('Predescu','Aura'),
('Ancuta','Ionuţ-Alin'),
('Koti','Danut Madalin'),
('Puscasu','Denisa Elena'),
('Dinut','Cosmin Daniel'),
('Constantinescu','Mugurel Adrian'),
('Cringanu','Alexandru Vlad'),
('Grigorian','Magda Marina'),
('Hotoi',' Roxana'),
('Harald-Cezar','Fesus'),
('Calcii','Adrian Stefan'),
('Angelescu','George-Marcel'),
('Banarescu','Laurentiu - Ionuţ '),
('Carcadia','Ana Maria'),
('Purcareanu','Alexandru Ovidiu '),
('Capatina','Dorel-Constantin'),
('Dohan','Moroianu'),
('Aureliu','Octavian-Mihail'),
('Turcanu','Burghelea'),
('Taranu','Aurel'),
('Sovarel','Ioana Laura'),
('Ghimpu','Reter'),
('Vladuta','Boby'),
('Mutulescu','Ioana-Lorina'),
('Cuconu','De Test'),
('Mihaita','Eugeniu'),
('Magla','Alexandru-Paul'),
('Mustatea','Alexandru Razvan'),
('Nichitean','Alexandru Adrian'),
('Fecioru','Habib'),
('Clitman','Alexander'),
('Pampu','Dorin-Mihai'),
('Nimigean','Alina Cristina'),
('Tudose','Alin-Ilie'),
('Guta','Iulia Maria'),
('Aciu','Crina'),
('Manea','Razvan-Gabriel'),
('Hodivoianu','Fanica'),
('Dragne','Mihaela-Viorica'),
('Chisa','Livius Codrut'),
('Ghit','Vladimir'),
('Calagiu','Bejan');



update Utilizator 
set email = lower(concat(replace(prenume, ' ',''), elt(0.5 + rand() * 3, '_','','.'), nume, '@', elt(0.5 + rand() * 5, 'gmail.com','yahoo.com','outlook.com','protonmail.com','aol.com'))) where email is null;

SET SQL_SAFE_UPDATES = 0;
update Utilizator set parola_criptata = 'parola' where parola_criptata is null;

ALTER TABLE Utilizator MODIFY nume_utilizator varchar(50) NULL;
update Utilizator set nume_utilizator = LEFT(email,INSTR(email,"@")-1);

update Utilizator set numar_autentificari = (FLOOR(RAND()*(150-50))+50);
update Utilizator set numar_invitatii = (FLOOR(RAND()*(5-1))+1);

update Utilizator set invitatie_creata_la = FROM_UNIXTIME(UNIX_TIMESTAMP('2018-01-30 14:53:27') + FLOOR(0 + (RAND() * 63072000)));
update Utilizator set ultima_autentificare = FROM_UNIXTIME(UNIX_TIMESTAMP('2020-01-30 14:53:27') + FLOOR(0 + (RAND() * 5259488)));

update Utilizator set invitatie_acceptata_la = FROM_UNIXTIME(UNIX_TIMESTAMP(invitatie_creata_la) + FLOOR(180 + (RAND() * 172800)));
update Utilizator set creat_la = FROM_UNIXTIME(UNIX_TIMESTAMP(invitatie_acceptata_la) + FLOOR(120 + (RAND() * 120)));
update Utilizator set actualizat_la = FROM_UNIXTIME(UNIX_TIMESTAMP(ultima_autentificare) - FLOOR(172800 + (RAND() * 5259488)));

update Utilizator set id_rol = 3 where id_rol is null;

alter table Utilizator modify ip_ultima_autentificare varchar (100);
update Utilizator set ip_ultima_autentificare = CONCAT(
  FLOOR(2 + (RAND() * 250)), '.' ,
  FLOOR(2 + (RAND() * 250)), '.' ,
  FLOOR(2 + (RAND() * 250)), '.' ,
  FLOOR(2 + (RAND() * 250))
);

update Utilizator set token_invitatie = 'ffO77H5RpZJMLcMJWTaMdfTrQOnEZe1j1muYAIKx6gidHechePHDe9oUSvT809mj' where token_invitatie is null;

update Utilizator set telefon = ELT(0.5 + RAND() * 119, "0761-600-926","0785-853-326","0743-586-713","0764-623-355","0774-128-523","0729-969-565","0721-412-439","0772-969-797","0781-969-370","0776-517-349","0725-821-878","0771-756-806","0776-914-683","0763-596-252","0774-034-320","0782-274-255","0761-583-251","0770-139-841","0785-970-268","0727-523-144","0721-156-096","0783-728-496","0736-768-365","0784-291-614","0723-194-510","0763-884-434","0723-136-085","0783-386-503","0726-213-820","0767-778-559","0779-484-246","0789-453-761","0779-813-562","0766-716-714","0747-193-575","0765-006-107","0742-905-842","0748-121-492","0784-532-164","0777-973-061","0774-144-697","0729-691-844","0738-325-676","0773-208-281","0780-479-271","0775-647-508","0731-432-812","0772-168-218","0773-286-877","0735-978-537","0730-244-883","0731-847-539","0784-719-271","0748-926-354","0720-448-277","0737-702-812","0781-217-542","0773-094-520","0763-959-749","0743-407-376","0776-770-003","0731-619-609","0760-785-444","0771-789-885","0721-010-773","0770-354-212","0729-633-927","0749-084-509","0775-669-350","0734-204-473","0783-766-713","0746-566-207","0744-363-262","0747-225-807","0738-768-807","0728-208-361","0742-971-321","0731-903-535","0776-525-846","0775-908-247","0725-244-841","0731-953-553","0737-327-256","0739-391-269","0780-773-180","0747-197-920","0721-298-095","0779-326-592","0731-836-366","0761-418-828","0768-256-936","0789-437-678","0720-450-349","0772-000-669","0781-900-427","0789-699-177","0736-502-056","0768-088-243","0731-364-386","0766-066-516","0778-190-570","0725-308-864","0735-032-934","0767-425-358","0785-296-686","0721-212-883","0739-086-896","0744-006-005","0788-599-870","0781-191-793","0779-011-205","0738-237-301","0788-193-367","0776-676-886","0744-654-493","0778-289-838","0760-751-657","0725-991-017","0721-674-489");

insert into Pacient (id_utilizator) select id_utilizator from Utilizator where id_rol = 3;

update Pacient set id_zona = FLOOR((RAND()*8) + 1);

update Pacient set id_asigurare = FLOOR((RAND()*4) + 1);

delimiter $

	create function genereazaData ()
		returns date
        not deterministic		/* rezultatul este de tip neterminist intrucat se foloseste functia rand() */
        comment 'Returneaza data de nastere pentru varsta cuprinse intre 20 si 90 de ani' /* valorile intervalului de varsta sunt prestabilite*/
        
        begin
        declare Dob date;
        declare anDob int;
        declare lunaDob int;
        declare ziDob int;
        
			select year(curdate())-round(20+rand()*60) into anDob;/* se alege o varsta aleatoare pe baza careia se calculeaza anul nasterii */
            select round(1+rand()*11) into lunaDob; /* se alege o luna de nastere aleatoare intre 1 si 12 */
            case /* pentru aflarea zilei de nastere se foloseste o structura decizionala case 
					pentru selectarea corecta a intervalului pentru ziua de nastere */
				when lunaDob=2 and anDob%4=0/* daca anul este bisect si luna este februarie atunci 
												intervalul pentru ziua de nastere este intre 1 si 29 */
					then select floor(1+rand()*29) into ziDob;
				when lunaDob=2 and anDob%4!=0/* daca anul NU este bisect si luna este februarie atunci 
												intervalul pentru ziua de nastere este intre 1 si 28 */
					then select floor(1+rand()*28) into ziDob;
				when lunaDob=1 or lunaDob=3 or lunaDob=5 or lunaDob=7 or lunaDob=8 or lunaDob=10 or lunaDob=12
					then select floor(1+rand()*31) into ziDob;/* daca luna este Ianuarie, Martie, Mai, Iulie, August, Octombrie sau Decembrie
																atunci intervalul pentru ziua de nastere este intre 1 si 31 */
				when lunaDob=4 or lunaDob=6 or lunaDob=9 or lunaDob=11/* daca luna este Aprilie, Iunie, Septembrie sau Noiembrie
																atunci intervalul pentru ziua de nastere este intre 1 si 30 */
					then select floor(1+rand()*30) into ziDob;
            end case;
            select concat(anDob,'-',lunaDob,'-',ziDob) into Dob;
        return Dob; /* se returneaza data de nastere intr-o variabila de tip date generata prin concatenarea datelor obtinute anterior*/
        
        end $
	
delimiter ;

update Pacient set data_nasterii=genereazaData();
